name: Build and Push hodr to ECR

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: bran
  IMAGE_TAG: v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr-public get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Tag and push image
        run: |
          docker tag $IMAGE_NAME ${{ secrets.ECR_URI }}:$IMAGE_TAG
          docker push ${{ secrets.ECR_URI }}:$IMAGE_TAG
